# Generated by Django 5.2 on 2025-05-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_type',
            new_name='type',
        ),
    ]
