# Generated by Django 5.2 on 2025-04-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_face_id_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='face_id',
        ),
    ]
