# Generated by Django 5.2 on 2025-05-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_service_type_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
    ]
