services:
  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    tty: true
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync+restart

  frontend:
    image: oven/bun:1
    working_dir: '/app'
    command: sh -c "bun install && bun run dev"
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
