services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Edge port for all services
      - "4571:4571"  # Optional: external API
    environment:
      - SERVICES=iam,s3,stepfunctions,dynamodb,lambda
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    tty: true
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync+restart
    depends_on:
      - database
      - localstack
    environment:
      - IS_LOCAL=true

  frontend:
    image: oven/bun:1
    working_dir: '/app'
    command: sh -c "bun install && bun run dev"
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

volumes:
  postgres:
  localstack_data: